version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow:
    image: apache/airflow:2.8.1
    depends_on:
      - postgres
      - kafka
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./kafka:/opt/airflow/kafka
    command: standalone

  spark:
    image: bitnami/spark:latest
    container_name: spark
    depends_on:
      - kafka
    volumes:
      - ./spark:/opt/spark-apps

  streamlit:
    image: python:3.9
    working_dir: /app
    volumes:
      - ./dashboard:/app
    command: >
      bash -c "
      pip install -r requirements.txt &&
      streamlit run app.py --server.port 8501 --server.address 0.0.0.0
      "
    ports:
      - "8501:8501"

  kafka-exporter:
    image: danielqsj/kafka-exporter
    ports:
      - "9308:9308"
    command:
      - '--kafka.server=kafka:9092'

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"